# Generated by Django 3.1.4 on 2022-09-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0130_auto_20210124_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
