# Generated by Django 3.1.4 on 2022-09-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlct', '0131_player_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
